### ISSUE TITLE
Mobile (Smartphone version) inconsistencies

### ISSUE THREAD

**Issue by darionewmonday** [wmde/mitmachen#56]
@dev-ckln We have noticed that some inconsistencies appear on mobile (smartphone):

1) The text in the search bar is too long and will be cut
2) apparently the Article´s preview is hard-coded to 1280px and not responsive, why?
3) The hamburger menu doesn´t produce any window
4) the link "preview article" is missing

Can you pls check?

**Comment by dev-ckln** [comment]
@darionewmonday 

1. The text in the search bar is too long and will be cut (done)
2. apparently the Article´s preview is hard-coded to 1280px and not responsive, why?
Because it is in iframe. So, the iframe content is not responsive. 
This page is for desktop only
Please clarify do we need to keep an other iframe for mobile that will display the mobile page?
3. The hamburger menu doesn´t produce any window (done)
-There is no menu item now, so removed hamburger
4. the link "preview article" is missing (done)

**Comment by darionewmonday** [comment]
@dev-ckln thanks.

2. The whole tool was agreed to be responsive. Thus we need also the preview to be responsive. The question would be, why it was not done responsive from the beginning?

**Comment by darionewmonday** [comment]
@dev-ckln Thanks now it looks good. The preview Article has also being made responsive. 

@ChristineDomgoergen
